# Generated by Django 3.1.2 on 2020-12-21 12:37

import ckeditor_uploader.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'showroom',
                'verbose_name_plural': 'showrooms',
            },
        ),
        migrations.AddField(
            model_name='setting',
            name='Mission',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='Vission',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
